//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagmentDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantManagementEntities : DbContext
    {
        public RestaurantManagementEntities()
            : base("name=RestaurantManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Customer> tbl_Customer { get; set; }
        public virtual DbSet<tbl_Employee> tbl_Employee { get; set; }
        public virtual DbSet<tbl_Factor> tbl_Factor { get; set; }
        public virtual DbSet<tbl_Food> tbl_Food { get; set; }
        public virtual DbSet<tbl_FoodStatus> tbl_FoodStatus { get; set; }
        public virtual DbSet<tbl_FoodType> tbl_FoodType { get; set; }
        public virtual DbSet<tbl_Order> tbl_Order { get; set; }
        public virtual DbSet<tbl_OrderFactor> tbl_OrderFactor { get; set; }
        public virtual DbSet<tbl_OrderKind> tbl_OrderKind { get; set; }
        public virtual DbSet<tbl_SexType> tbl_SexType { get; set; }
    }
}
