//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagmentDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Factor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Factor()
        {
            this.tbl_OrderFactor = new HashSet<tbl_OrderFactor>();
        }
    
        public int FactorID { get; set; }
        public string SumFactor { get; set; }
        public string Discount { get; set; }
        public string OrderDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string tax { get; set; }
        public Nullable<int> OrderKindID { get; set; }
        public string PdfFileAddress { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Employee tbl_Employee { get; set; }
        public virtual tbl_OrderKind tbl_OrderKind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_OrderFactor> tbl_OrderFactor { get; set; }
    }
}
