//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagmentDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OrderFactor
    {
        public int OrderFactorID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> FactorID { get; set; }
    
        public virtual tbl_Factor tbl_Factor { get; set; }
        public virtual tbl_Order tbl_Order { get; set; }
    }
}
